name: Test upload


on:
  pull_request_target:
    branches: [ master ]


jobs:
  test-upload-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCS_SERVICE_ACCOUNT }}'

      - run: echo Hello > test.txt

      - name: 'Upload to GCS'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'test.txt'
          destination: 'radu-codecov-public/pr/'
