name: Test2

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master ]

jobs:
  linux:
    name: test-job2
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: '${{ github.event.pull_request.number }}'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.1
      - run: bash -c 'echo $PR_NUMBER'
