name: Test

on:
  pull_request:
    branches:
    - master

jobs:

  linux:
    name: go-linux
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20.1"

    - run: bash -c 'echo $PR_NUMBER'
